In [4]:
#2.3.1
16*25

400

In [5]:
#2.3.2 
1000

1000

In [6]:
#2.3.3 
в

NameError: name 'в' is not defined

In [7]:
#2.4.1
(2.4*200)-300

180.0

In [8]:
2*0.1+3*0.2+4*0.6+5*0.1

3.7

In [9]:
(2+3+4+5)/4

3.5

In [10]:
(2-3.5)**2*0.1+(3-3.5)**2*0.2+(4-3.5)**2*0.6+(5-3.5)**2*0.1

0.65

In [11]:
0.65**(1/2)

0.806225774829855

In [12]:
a=(38+39+40+41+42+43)/6
a

40.5

In [13]:
a*10+20

425.0

In [14]:
(38-a)**2*0.1+(39-a)**2*0.1+(40-a)**2*0.3+(41-a)**2*0.2+(42-a)**2*0.2+(43-a)**2*0.1

2.05

In [15]:
2.05**(1/2)

1.4317821063276353

In [16]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([0.2,0.1,0.4,0.3])

In [17]:
c=a*b
c

array([0.2, 0.2, 1.2, 1.2])

In [18]:

#e(x)
e_x=c.sum()
e_x

2.8

In [19]:
e=(a-2.8)**2
e

array([3.24, 0.64, 0.04, 1.44])

In [20]:
round(e.sum(),2)

5.36

In [21]:
# e(u)
e_x*3+1

9.399999999999999

In [22]:
#d_u


In [23]:
#2.8
from scipy.stats import norm
#2.8.1
norm.cdf(1)

0.8413447460685429

In [24]:
norm.cdf(1.12)

0.8686431189572693

In [25]:
norm.cdf(0,-1.87)

0.9692580910705341

In [26]:
norm.cdf(0,-1.87)

0.9692580910705341

In [27]:
round(norm.ppf(0.1),2)

-1.28

In [28]:
round(1-norm.ppf(0.05),2)

2.64

In [29]:
round(norm.ppf(0.025),2)

-1.96

In [30]:
round(1-norm.ppf(0.01),2)

3.33

In [31]:
round(norm.ppf(0.005),2)

-2.58

In [32]:
round(1 - norm.cdf(75, 70, 5 / (5 ** 0.5)), 3)

0.013

In [33]:
0.3*400+0.4*400+0.3*400

400.0

In [34]:
import numpy as np
a=np.array([2,3,4,5])
b=np.array([0.1,0.2,0.6,0.2])

In [35]:
c=a*b

In [36]:
c.sum()

4.2

In [37]:
4.2*5.2

21.840000000000003

In [38]:
norm.ppf(0.05,700,130)

486.16902849630856

In [39]:
norm.cdf(486,700,130)

0.04986604439219501

In [40]:
# 2/8
from scipy.stats import norm

In [41]:
 norm.cdf(1.5)

0.9331927987311419

In [42]:
#2/8/1
norm.cdf(1)

0.8413447460685429

In [43]:
norm.cdf(1.12)

0.8686431189572693

In [44]:
1-norm.cdf(1.87)

0.030741908929465933

In [45]:
1-norm.cdf(2)

0.02275013194817921

In [46]:
#2.8.2
norm.ppf(0.1)

-1.2815515655446004

In [47]:
-norm.ppf(0.05)

1.6448536269514729

In [48]:
norm.ppf(0.025)

-1.9599639845400545

In [49]:
-norm.ppf(0.01)

2.3263478740408408

In [50]:
norm.ppf(0.005)

-2.575829303548901

In [ ]:
#2.10.1


In [53]:
#mean weight < 75
norm.cdf(75,70,5/(5**0.5))

0.9873263406612659

In [54]:
1-norm.cdf(75,70,5/(5**0.5))

0.0126736593387341

In [57]:
#2.10.2
a=(0.2*0.8/225)**0.5
norm.cdf(0.16,0.2,a)

0.06680720126885807

In [58]:
#2.11.1
0.3*400+0.4*800+0.3*1200

800.0

In [59]:
#2.11.2
2*0.1+3*0.2+4*0.6+5*0.1

3.7

In [63]:
import numpy as np
a=np.array([2,3,4,5])
b=np.array([0.1,0.2,0.6,0.1])
c=a*b
c

array([0.2, 0.6, 2.4, 0.5])

c.sum()

In [64]:
c.sum()

3.7

In [65]:
f=a*a
f

array([ 4,  9, 16, 25])

In [66]:
e=f*b
e

array([0.4, 1.8, 9.6, 2.5])

In [67]:
e.sum()

14.3

In [68]:
1-norm.cdf(820,700,120)

0.15865525393145707

In [70]:
norm.cdf(820,700,120)-norm.cdf(730,700,120)

0.24263842038561922

In [71]:
norm.ppf(0.05,700,120)

502.61756476582326

In [72]:
12.35-(1.9*2.4/8)

11.78

In [73]:
12.35+(1.9*2.4/8)

12.92