In [1]:
import numpy as np

In [2]:
s=np.array([30,65,50,45])

In [3]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

In [4]:
print("ndim:", s.ndim)

ndim: 1


In [9]:
print("shape:", s.shape)
s[1]

shape: (4,)


65

In [7]:
import numpy as np
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])
share_living_space = apartment[1]/apartment[0]
share_living_space

0.5277310924369748

In [11]:
apartment = np.delete(apartment, [0, 1])
apartment

array([6.055e+04, 2.000e+00])

In [13]:
apartment = np.append(apartment, share_living_space)
apartment

array([6.05500000e+04, 2.00000000e+00, 5.27731092e-01, 5.27731092e-01])

In [14]:
apartment.shape

(4,)

In [15]:
apartment.ndim

1

In [16]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
t.mean()

21.25

In [18]:
s=np.array([2,3,2.5])
s=s*72

In [19]:
a=np.array([120,150,90])
b=np.array([130,130,130])
a+b+s

array([394., 496., 400.])

In [22]:
x=np.array([4,5])
y=np.array([2,1])
u=np.array([1,0])
2*x+(-3*y)+5*u

array([7, 7])

In [23]:
x=np.array([4,6,1])
np.linalg.norm(x)

7.280109889280518