In [2]:
0.1/(0.7+0.1)

0.12500000000000003

In [3]:
2.5/80

3.125

In [1]:
0.78*0.04

0.031200000000000002

In [2]:
0.0312+0.02+0.014

0.0652

In [3]:
0.0312/0.06525

0.4781609195402298

In [4]:
0.7*0.02+0.1*0.2+0.04*0.78

0.06520000000000001

In [7]:
0.7*0.02/0.0652

0.2147239263803681

In [8]:
0.04*0.78/0.0652

0.47852760736196326

In [9]:
1-0.0652

0.9348

In [10]:
0.96*0.78/0.9348

0.8010269576379975

In [11]:
1-0.0295

0.9705

In [12]:
0.03*0.01/0.9705

0.00030911901081916534

In [1]:
0.09*0.4

0.036

In [3]:
0-0.5+0.2+0.2

-0.09999999999999998

In [4]:
0.5

0.5

In [5]:
0.07*5000

350.00000000000006

In [6]:
0.5/0.6

0.8333333333333334

In [7]:
1/36

0.027777777777777776

In [8]:
4/9

0.4444444444444444

In [9]:
1/18

0.05555555555555555

In [10]:
1/16

0.0625

In [11]:
import math

In [12]:
math.sqrt(0.2)

0.4472135954999579

In [13]:
math.sqrt(0.4)

0.6324555320336759

In [14]:
0.02/(math.sqrt(0.2)*math.sqrt(0.4))

0.07071067811865475

In [2]:
import numpy as np

In [3]:
math = np.array([20,23,29,22,50,43,35])
rus = np.array([70,65,58,90,45,57,50])

In [4]:
2/7

0.2857142857142857

In [44]:
math.mean()

31.714285714285715

In [11]:
np.median(rus)

58.0

In [12]:
np.std(math)

10.606120681868907

In [13]:
np.std(rus)

13.788489728015605

In [45]:
m=np.array(([x-31.71 for x in math]))
m

array([-11.71,  -8.71,  -2.71,  -9.71,  18.29,  11.29,   3.29])

In [46]:
a=np.array(([x-62.14 for x in rus]))
a

array([  7.86,   2.86,  -4.14,  27.86, -17.14,  -5.14, -12.14])

In [47]:
b=np.array([x**2 for x in a])
b

array([ 61.7796,   8.1796,  17.1396, 776.1796, 293.7796,  26.4196,
       147.3796])

In [48]:
c=np.sqrt(sum(b)/len(b))
c

13.788490024032985

In [43]:
np.correlate(rus,math,mode='same')

array([10434, 11805, 13201, 13008, 11234,  8289,  5588])

In [50]:
sum(m)

0.02999999999999403